# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'platformio-esp32:$(espressif32_version)'

steps:
  - script: |
      docker login -u $(dockerid) -p $(pwd) $(registry)
    displayName: 'docker login'

  - script: |
      docker build -t $(registry)/$(imageName) --build-arg espressif32_version=$(espressif32_version) .
    displayName: 'docker build'

  - script: |
      docker push $(registry)/$(imageName)
    displayName: 'docker push'
